### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by santomet** [X-Stuff/CudaKeeloq#1]
Hello, a simple question - does your tool find only the crypt key or the manufacturer key?

I have an idea of having a 64-bit window and going through the binary firmware of the receiver bit-by-bit to find out the manufacturer's key.
Does that make sense?

**Comment by X-Stuff** [comment]
If I understood your question correct - this bruteforcer tries to find manufacturer key or specific device key - imagine any car, it would be very strange if “manufacturer” (e.g Toyota) would use single key for every car in the world, most probably each car has its own key.

However, to be sure that bruted key is correct it should be checked at least on 3 consecutive transmissions. 

If you have only 1 transmission - it’s impossible to find correct “manufacturer” key, since collision rate of 18bit part of serial and 4bit button code is incredibly high.

If you have 3+ transmissions - and the tool has found a match - I would say it’s almost 100% chance you’ve found what you want.

And answering your question.
Yes it makes sense, but only in case when firmware has this key RAW, without any encoding or any other protection. Key is just a 64bit number, in a firmware it might be obtained just with simple addition of two numbers.
However if you have 3 inputs for the tool, and bit-by-bit window gave you a match - it’s you lucky day, and a bad one for firmware developer :)
