### ISSUE TITLE
Help running on Ubuntu 22.04

### ISSUE THREAD

**Issue by ste94pz** [X-Stuff/CudaKeeloq#4]
Hi, could you help me to run it on Ubuntu? I tried with this command line, but it always shows the help and it says "Not enough arguments for bruteforce"

./run.sh --inputs 0x0123456789ABCDEF,0x123456789ABCDEF0,0x23456789ABCDEF01 --mode=5 --learning-type=8 --start=0x3456789ABCDEF012

Thank you, and sorry if this is a stupid question.

**Comment by X-Stuff** [comment]
Hello, yes sorry about that.
The `entrypoint` in dockerfile might not be quite correct.

In fact every time you launching `./run.sh <args>` you invoking something like
```
/app/CudaKeeloq --help <args>
``` 
since `--help` argument has bigger priority it executes instead of bruteforce

Luckily you can override `entrypoint` like this:

```
DOCKER_ARGS="--entrypoint ./CudaKeeloq" ./run.sh  --inputs 0x0123456789ABCDEF,0x123456789ABCDEF0,0x23456789ABCDEF01 --mode=5 --learning-type=8 --start=0x3456789ABCDEF012
```

This should help.

**Comment by X-Stuff** [comment]
Version updated to `0.1.2`
Checkout master, rebuild docker image, and you will be able to use it as you initially wanted: `./run.sh <args>`
